---
- gather_facts: false
  hosts: all
  sudo: yes
  vars:
  - roles_path: /home/phucph2
  - products: DNMM

  tasks:
  - name: create user test
    user: name=test groups=wheel state=present
  - name: USER key test
    authorized_key: user="test" key="{{ lookup('file', '{{ playbook_dir }}/templates/keys/test') }}" state=present
