---
- hosts: all
  gather_facts: no
  tasks:
  - name: list files on folder
    command: ls -lai /tmp/
  - name: get /use/aa.txt contain
    command: cat /root/.bash_profile
  - name: Get memory status.
    shell: free -m
