---
- hosts: all
  tasks:
  - name: list files in folder
    command: ls -lai /tmp/
    register: tmp_list_file
  - name: get /use/aa.txt contain
    command: cat /root/.bash_profile
    register: result
  
