---
- hosts: all
  gather_facts: no
  tasks:
  - name: list files on folder
    command: ls -lai /tmp/
    ignore_errors: yes
    check_mode: no
  - name: get /use/aa.txt contain
    command: cat /root/.bash_profile
    ignore_errors: yes
    check_mode: no
  - name: Get memory status.
    shell: free -m
    ignore_errors: yes
    check_mode: no
  - name: this task will be skipped in check mode
    git:
      repo: https://github.com/hhthuongbtr/ansible.ls/blob/master/ls.yml
      dest: /tmp/
