---
- hosts: all
  tasks:
  - name: list files on folder
    command: ls -lai /tmp/
    ignore_errors: yes
  - name: get /use/aa.txt contain
    command: cat /root/.bash_profile
    ignore_errors: yes
  - name: Get memory status.
    shell: free -m
    ignore_errors: yes
  - name: clone git task
    git:
      repo: https://github.com/hhthuongbtr/ansible.ls.git
      dest: /tmp/
