---
- hosts: all
  tasks:
  - name: list files on folder
    command: ls -lai /home
    ignore_errors: yes
  - name: get /use/aa.txt contain
    command: cat /root/.bash_profile
    ignore_errors: yes
  - name: Get memory status.
    shell: free -m
    ignore_errors: no
